### PR TITLE
Ensure legacy aliases works on Symfony 3.0

### PR DESCRIPTION
**Pull request by pamil**

### CODE REVIEW

**Comment by isometriks** [comment]
:thumbsup: thanks man. Made you a collaborator as well. Not sure why they couldn't support this in Symfony itself, Id have to look back at the commit that took it out but I can't see how the small lookup array would affect performance that adversely

**Comment by pamil** [comment]
@isometriks no problem! I've seen that, but I still prefer to send PRs as the more eyes on code the better :) I don't understand that decision as well. 

Anyway, I think this bundle is ready for some real project on it, but there can still be an issue related to `FormTypeInterface::getName()` being to `FormTypeInterface::getBlockPrefix`. Right now, Symfony <=2.7 forms will not be able to connect themselves with customized Twig blocks.

**Comment by isometriks** [comment]
Totally, makes sense. And you're right, that would be a problem, but I had imagined this was more of a backwards compatibility thing so only >= 2.8 would be using this (as this functionality exists otherwise). Not aiming to give that Twig customization to older versions, just allow the form type by alias in versions where it's not possible so you won't have to override any form that uses a class you don't want.  

Would it be wise to test for Symfony version in the extension and not load the services / compiler pass if it's <= 2.7? That way for instance Sylius could always include the bundle but it will just do nothing if it's not needed? Or will they have different kernels for each version so it won't be included anyway? (Or not support both versions simultaneously)

**Comment by pamil** [comment]
@isometriks IMHO this bundle should be allowed for projects using Symfony `^2.8|^3.0`, but should support third-party bundles that were written / do not support new syntax.

This way, the usual workflow for updating from 2.7 to 3.0 should apply - update to 2.8, fix deprecations, update to 3.0. The form alias related deprecations will be automatically covered by this bundle.

As for the templating issue, I've got some idea - for every service tagged with `form.type` having `alias` option, we should return custom `ResolvedFormTypeInterface` with overriden `getBlockPrefix()` method. We can check at compile-time whether it has `getName()` method defined and if so, assume it's an old-style one and use `getName()` instead of `getBlockPrefix()`.

If the form type has both `getName()` and `getBlockPrefix()`, there's no problem, as they surely be the same (no reason to do anything else, edge case anyway).

**Comment by pamil** [comment]
As for Sylius, it will jump to PHP 5.6 (Sylius/Sylius#4567) and probably simultaneously to Symfony 2.8 (RFC incoming :)) in the next minor, so we'll be able to make use of this bundle.

I've given the templating issue another thought and I'll agree with you that we don't need so much complexity here (and my idea it's quite magic).

That being said, after #4 I don't see any issues or not tested scenarios, so we might tag a RC release :tada:

**Pull request merged**
